### ISSUE TITLE
using processing for 3D image mapping

### ISSUE THREAD

**Issue by mkeyno** [grayfuse/sva-slowcode-2014#4]
hi
first of all I'm so sorry to open ticket for my question but I thought may I could have your guide to my 3D image issue , and I really appreciated if you could direct me to correct links or track
actually I'm Arduino Neopixel fan and tried to run the spherical POV. For run POV, each image should be converted to the number of lines which is used in each revolution , I think convert the planner POV must not be so hard for java base processing to pixelizid into lines but I don't now how to map an image on spherical and then converted to image lines
thanks again

**Comment by nicbarajas** [comment]
I don’t think we’re going to be able to help here. As a class of students who were understanding the basics of Arduino and Processing, we’re in no position for this. (Also, spamming random projects is probably not a helpful way to ask for help.)
